/**
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Count Json</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.CountJson#getCountJSON <em>Count JSON</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.CountJson#getPath <em>Path</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCountJson()
 * @model
 * @generated
 */
public interface CountJson extends Fun
{
  /**
   * Returns the value of the '<em><b>Count JSON</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Count JSON</em>' attribute.
   * @see #setCountJSON(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCountJson_CountJSON()
   * @model
   * @generated
   */
  String getCountJSON();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.CountJson#getCountJSON <em>Count JSON</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Count JSON</em>' attribute.
   * @see #getCountJSON()
   * @generated
   */
  void setCountJSON(String value);

  /**
   * Returns the value of the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' attribute.
   * @see #setPath(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCountJson_Path()
   * @model
   * @generated
   */
  String getPath();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.CountJson#getPath <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' attribute.
   * @see #getPath()
   * @generated
   */
  void setPath(String value);

} // CountJson
