/**
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Sentences</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SENTENCES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FunImpl <em>Fun</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FunImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFun()
   * @generated
   */
  int FUN = 1;

  /**
   * The number of structural features of the '<em>Fun</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUN_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CountJsonImpl <em>Count Json</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CountJsonImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCountJson()
   * @generated
   */
  int COUNT_JSON = 2;

  /**
   * The feature id for the '<em><b>Count JSON</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT_JSON__COUNT_JSON = FUN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT_JSON__PATH = FUN_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Count Json</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT_JSON_FEATURE_COUNT = FUN_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ReadJsonImpl <em>Read Json</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ReadJsonImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getReadJson()
   * @generated
   */
  int READ_JSON = 3;

  /**
   * The feature id for the '<em><b>Read JSON</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_JSON__READ_JSON = FUN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_JSON__PATH = FUN_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Read Json</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_JSON_FEATURE_COUNT = FUN_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.WriteJsonImpl <em>Write Json</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.WriteJsonImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWriteJson()
   * @generated
   */
  int WRITE_JSON = 4;

  /**
   * The feature id for the '<em><b>Write JSON</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_JSON__WRITE_JSON = FUN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_JSON__PATH = FUN_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_JSON__FILE = FUN_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Write Json</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_JSON_FEATURE_COUNT = FUN_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.WriteCSVImpl <em>Write CSV</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.WriteCSVImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWriteCSV()
   * @generated
   */
  int WRITE_CSV = 5;

  /**
   * The feature id for the '<em><b>Write CSV</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_CSV__WRITE_CSV = FUN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_CSV__PATH = FUN_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Tab Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_CSV__TAB_NAME = FUN_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Header</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_CSV__HEADER = FUN_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Output File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_CSV__OUTPUT_FILE = FUN_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Write CSV</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_CSV_FEATURE_COUNT = FUN_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RemoveImpl <em>Remove</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RemoveImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRemove()
   * @generated
   */
  int REMOVE = 6;

  /**
   * The feature id for the '<em><b>Remove Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE__REMOVE_ELEMENT = FUN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE__ID = FUN_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Tab Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE__TAB_NAME = FUN_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE__FILE = FUN_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Remove</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_FEATURE_COUNT = FUN_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AddImpl <em>Add</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AddImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAdd()
   * @generated
   */
  int ADD = 7;

  /**
   * The feature id for the '<em><b>Add Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD__ADD_ELEMENT = FUN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD__FILE = FUN_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD__ID = FUN_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Add</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_FEATURE_COUNT = FUN_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.GetImpl <em>Get</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.GetImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getGet()
   * @generated
   */
  int GET = 8;

  /**
   * The feature id for the '<em><b>Get Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET__GET_ELEMENT = FUN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET__FILE = FUN_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Get</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_FEATURE_COUNT = FUN_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SortImpl <em>Sort</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SortImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSort()
   * @generated
   */
  int SORT = 9;

  /**
   * The feature id for the '<em><b>Sort</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORT__SORT = FUN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORT__FILE = FUN_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Attribute</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORT__ATTRIBUTE = FUN_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Sort</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORT_FEATURE_COUNT = FUN_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.JSONImpl <em>JSON</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.JSONImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getJSON()
   * @generated
   */
  int JSON = 10;

  /**
   * The feature id for the '<em><b>Attribute</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON__ATTRIBUTE = 0;

  /**
   * The feature id for the '<em><b>Value STR</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON__VALUE_STR = 1;

  /**
   * The feature id for the '<em><b>Value INT</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON__VALUE_INT = 2;

  /**
   * The feature id for the '<em><b>Value ID</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON__VALUE_ID = 3;

  /**
   * The number of structural features of the '<em>JSON</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getSentences <em>Sentences</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sentences</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getSentences()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Sentences();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Fun <em>Fun</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fun</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fun
   * @generated
   */
  EClass getFun();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.CountJson <em>Count Json</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Count Json</em>'.
   * @see org.xtext.example.mydsl.myDsl.CountJson
   * @generated
   */
  EClass getCountJson();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.CountJson#getCountJSON <em>Count JSON</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Count JSON</em>'.
   * @see org.xtext.example.mydsl.myDsl.CountJson#getCountJSON()
   * @see #getCountJson()
   * @generated
   */
  EAttribute getCountJson_CountJSON();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.CountJson#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.mydsl.myDsl.CountJson#getPath()
   * @see #getCountJson()
   * @generated
   */
  EAttribute getCountJson_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ReadJson <em>Read Json</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Read Json</em>'.
   * @see org.xtext.example.mydsl.myDsl.ReadJson
   * @generated
   */
  EClass getReadJson();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ReadJson#getReadJSON <em>Read JSON</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Read JSON</em>'.
   * @see org.xtext.example.mydsl.myDsl.ReadJson#getReadJSON()
   * @see #getReadJson()
   * @generated
   */
  EAttribute getReadJson_ReadJSON();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ReadJson#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.mydsl.myDsl.ReadJson#getPath()
   * @see #getReadJson()
   * @generated
   */
  EAttribute getReadJson_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.WriteJson <em>Write Json</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Write Json</em>'.
   * @see org.xtext.example.mydsl.myDsl.WriteJson
   * @generated
   */
  EClass getWriteJson();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.WriteJson#getWriteJSON <em>Write JSON</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Write JSON</em>'.
   * @see org.xtext.example.mydsl.myDsl.WriteJson#getWriteJSON()
   * @see #getWriteJson()
   * @generated
   */
  EAttribute getWriteJson_WriteJSON();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.WriteJson#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.mydsl.myDsl.WriteJson#getPath()
   * @see #getWriteJson()
   * @generated
   */
  EAttribute getWriteJson_Path();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.WriteJson#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>File</em>'.
   * @see org.xtext.example.mydsl.myDsl.WriteJson#getFile()
   * @see #getWriteJson()
   * @generated
   */
  EReference getWriteJson_File();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.WriteCSV <em>Write CSV</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Write CSV</em>'.
   * @see org.xtext.example.mydsl.myDsl.WriteCSV
   * @generated
   */
  EClass getWriteCSV();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.WriteCSV#getWriteCSV <em>Write CSV</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Write CSV</em>'.
   * @see org.xtext.example.mydsl.myDsl.WriteCSV#getWriteCSV()
   * @see #getWriteCSV()
   * @generated
   */
  EAttribute getWriteCSV_WriteCSV();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.WriteCSV#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.mydsl.myDsl.WriteCSV#getPath()
   * @see #getWriteCSV()
   * @generated
   */
  EAttribute getWriteCSV_Path();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.WriteCSV#getTabName <em>Tab Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tab Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.WriteCSV#getTabName()
   * @see #getWriteCSV()
   * @generated
   */
  EAttribute getWriteCSV_TabName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.WriteCSV#getHeader <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Header</em>'.
   * @see org.xtext.example.mydsl.myDsl.WriteCSV#getHeader()
   * @see #getWriteCSV()
   * @generated
   */
  EAttribute getWriteCSV_Header();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.WriteCSV#getOutputFile <em>Output File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Output File</em>'.
   * @see org.xtext.example.mydsl.myDsl.WriteCSV#getOutputFile()
   * @see #getWriteCSV()
   * @generated
   */
  EAttribute getWriteCSV_OutputFile();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Remove <em>Remove</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Remove</em>'.
   * @see org.xtext.example.mydsl.myDsl.Remove
   * @generated
   */
  EClass getRemove();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Remove#getRemoveElement <em>Remove Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Remove Element</em>'.
   * @see org.xtext.example.mydsl.myDsl.Remove#getRemoveElement()
   * @see #getRemove()
   * @generated
   */
  EAttribute getRemove_RemoveElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Remove#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.mydsl.myDsl.Remove#getId()
   * @see #getRemove()
   * @generated
   */
  EAttribute getRemove_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Remove#getTabName <em>Tab Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tab Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Remove#getTabName()
   * @see #getRemove()
   * @generated
   */
  EAttribute getRemove_TabName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Remove#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>File</em>'.
   * @see org.xtext.example.mydsl.myDsl.Remove#getFile()
   * @see #getRemove()
   * @generated
   */
  EAttribute getRemove_File();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Add <em>Add</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add</em>'.
   * @see org.xtext.example.mydsl.myDsl.Add
   * @generated
   */
  EClass getAdd();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Add#getAddElement <em>Add Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Add Element</em>'.
   * @see org.xtext.example.mydsl.myDsl.Add#getAddElement()
   * @see #getAdd()
   * @generated
   */
  EAttribute getAdd_AddElement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Add#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>File</em>'.
   * @see org.xtext.example.mydsl.myDsl.Add#getFile()
   * @see #getAdd()
   * @generated
   */
  EReference getAdd_File();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Add#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.mydsl.myDsl.Add#getId()
   * @see #getAdd()
   * @generated
   */
  EAttribute getAdd_Id();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Get <em>Get</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Get</em>'.
   * @see org.xtext.example.mydsl.myDsl.Get
   * @generated
   */
  EClass getGet();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Get#getGetElement <em>Get Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Get Element</em>'.
   * @see org.xtext.example.mydsl.myDsl.Get#getGetElement()
   * @see #getGet()
   * @generated
   */
  EAttribute getGet_GetElement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Get#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>File</em>'.
   * @see org.xtext.example.mydsl.myDsl.Get#getFile()
   * @see #getGet()
   * @generated
   */
  EReference getGet_File();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Sort <em>Sort</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sort</em>'.
   * @see org.xtext.example.mydsl.myDsl.Sort
   * @generated
   */
  EClass getSort();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Sort#getSort <em>Sort</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sort</em>'.
   * @see org.xtext.example.mydsl.myDsl.Sort#getSort()
   * @see #getSort()
   * @generated
   */
  EAttribute getSort_Sort();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Sort#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>File</em>'.
   * @see org.xtext.example.mydsl.myDsl.Sort#getFile()
   * @see #getSort()
   * @generated
   */
  EReference getSort_File();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Sort#getAttribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attribute</em>'.
   * @see org.xtext.example.mydsl.myDsl.Sort#getAttribute()
   * @see #getSort()
   * @generated
   */
  EAttribute getSort_Attribute();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.JSON <em>JSON</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON</em>'.
   * @see org.xtext.example.mydsl.myDsl.JSON
   * @generated
   */
  EClass getJSON();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.JSON#getAttribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Attribute</em>'.
   * @see org.xtext.example.mydsl.myDsl.JSON#getAttribute()
   * @see #getJSON()
   * @generated
   */
  EAttribute getJSON_Attribute();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.JSON#getValueSTR <em>Value STR</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value STR</em>'.
   * @see org.xtext.example.mydsl.myDsl.JSON#getValueSTR()
   * @see #getJSON()
   * @generated
   */
  EAttribute getJSON_ValueSTR();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.JSON#getValueINT <em>Value INT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value INT</em>'.
   * @see org.xtext.example.mydsl.myDsl.JSON#getValueINT()
   * @see #getJSON()
   * @generated
   */
  EAttribute getJSON_ValueINT();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.JSON#getValueID <em>Value ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value ID</em>'.
   * @see org.xtext.example.mydsl.myDsl.JSON#getValueID()
   * @see #getJSON()
   * @generated
   */
  EAttribute getJSON_ValueID();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Sentences</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SENTENCES = eINSTANCE.getModel_Sentences();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FunImpl <em>Fun</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FunImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFun()
     * @generated
     */
    EClass FUN = eINSTANCE.getFun();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CountJsonImpl <em>Count Json</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CountJsonImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCountJson()
     * @generated
     */
    EClass COUNT_JSON = eINSTANCE.getCountJson();

    /**
     * The meta object literal for the '<em><b>Count JSON</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COUNT_JSON__COUNT_JSON = eINSTANCE.getCountJson_CountJSON();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COUNT_JSON__PATH = eINSTANCE.getCountJson_Path();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ReadJsonImpl <em>Read Json</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ReadJsonImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getReadJson()
     * @generated
     */
    EClass READ_JSON = eINSTANCE.getReadJson();

    /**
     * The meta object literal for the '<em><b>Read JSON</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute READ_JSON__READ_JSON = eINSTANCE.getReadJson_ReadJSON();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute READ_JSON__PATH = eINSTANCE.getReadJson_Path();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.WriteJsonImpl <em>Write Json</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.WriteJsonImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWriteJson()
     * @generated
     */
    EClass WRITE_JSON = eINSTANCE.getWriteJson();

    /**
     * The meta object literal for the '<em><b>Write JSON</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WRITE_JSON__WRITE_JSON = eINSTANCE.getWriteJson_WriteJSON();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WRITE_JSON__PATH = eINSTANCE.getWriteJson_Path();

    /**
     * The meta object literal for the '<em><b>File</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WRITE_JSON__FILE = eINSTANCE.getWriteJson_File();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.WriteCSVImpl <em>Write CSV</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.WriteCSVImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWriteCSV()
     * @generated
     */
    EClass WRITE_CSV = eINSTANCE.getWriteCSV();

    /**
     * The meta object literal for the '<em><b>Write CSV</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WRITE_CSV__WRITE_CSV = eINSTANCE.getWriteCSV_WriteCSV();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WRITE_CSV__PATH = eINSTANCE.getWriteCSV_Path();

    /**
     * The meta object literal for the '<em><b>Tab Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WRITE_CSV__TAB_NAME = eINSTANCE.getWriteCSV_TabName();

    /**
     * The meta object literal for the '<em><b>Header</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WRITE_CSV__HEADER = eINSTANCE.getWriteCSV_Header();

    /**
     * The meta object literal for the '<em><b>Output File</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WRITE_CSV__OUTPUT_FILE = eINSTANCE.getWriteCSV_OutputFile();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RemoveImpl <em>Remove</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RemoveImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRemove()
     * @generated
     */
    EClass REMOVE = eINSTANCE.getRemove();

    /**
     * The meta object literal for the '<em><b>Remove Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REMOVE__REMOVE_ELEMENT = eINSTANCE.getRemove_RemoveElement();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REMOVE__ID = eINSTANCE.getRemove_Id();

    /**
     * The meta object literal for the '<em><b>Tab Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REMOVE__TAB_NAME = eINSTANCE.getRemove_TabName();

    /**
     * The meta object literal for the '<em><b>File</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REMOVE__FILE = eINSTANCE.getRemove_File();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AddImpl <em>Add</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AddImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAdd()
     * @generated
     */
    EClass ADD = eINSTANCE.getAdd();

    /**
     * The meta object literal for the '<em><b>Add Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADD__ADD_ELEMENT = eINSTANCE.getAdd_AddElement();

    /**
     * The meta object literal for the '<em><b>File</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD__FILE = eINSTANCE.getAdd_File();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADD__ID = eINSTANCE.getAdd_Id();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.GetImpl <em>Get</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.GetImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getGet()
     * @generated
     */
    EClass GET = eINSTANCE.getGet();

    /**
     * The meta object literal for the '<em><b>Get Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GET__GET_ELEMENT = eINSTANCE.getGet_GetElement();

    /**
     * The meta object literal for the '<em><b>File</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GET__FILE = eINSTANCE.getGet_File();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SortImpl <em>Sort</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SortImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSort()
     * @generated
     */
    EClass SORT = eINSTANCE.getSort();

    /**
     * The meta object literal for the '<em><b>Sort</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SORT__SORT = eINSTANCE.getSort_Sort();

    /**
     * The meta object literal for the '<em><b>File</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SORT__FILE = eINSTANCE.getSort_File();

    /**
     * The meta object literal for the '<em><b>Attribute</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SORT__ATTRIBUTE = eINSTANCE.getSort_Attribute();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.JSONImpl <em>JSON</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.JSONImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getJSON()
     * @generated
     */
    EClass JSON = eINSTANCE.getJSON();

    /**
     * The meta object literal for the '<em><b>Attribute</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON__ATTRIBUTE = eINSTANCE.getJSON_Attribute();

    /**
     * The meta object literal for the '<em><b>Value STR</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON__VALUE_STR = eINSTANCE.getJSON_ValueSTR();

    /**
     * The meta object literal for the '<em><b>Value INT</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON__VALUE_INT = eINSTANCE.getJSON_ValueINT();

    /**
     * The meta object literal for the '<em><b>Value ID</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON__VALUE_ID = eINSTANCE.getJSON_ValueID();

  }

} //MyDslPackage
