/**
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Read Json</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ReadJson#getReadJSON <em>Read JSON</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ReadJson#getPath <em>Path</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getReadJson()
 * @model
 * @generated
 */
public interface ReadJson extends Fun
{
  /**
   * Returns the value of the '<em><b>Read JSON</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Read JSON</em>' attribute.
   * @see #setReadJSON(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getReadJson_ReadJSON()
   * @model
   * @generated
   */
  String getReadJSON();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ReadJson#getReadJSON <em>Read JSON</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Read JSON</em>' attribute.
   * @see #getReadJSON()
   * @generated
   */
  void setReadJSON(String value);

  /**
   * Returns the value of the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' attribute.
   * @see #setPath(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getReadJson_Path()
   * @model
   * @generated
   */
  String getPath();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ReadJson#getPath <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' attribute.
   * @see #getPath()
   * @generated
   */
  void setPath(String value);

} // ReadJson
