/**
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Remove</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Remove#getRemoveElement <em>Remove Element</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Remove#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Remove#getTabName <em>Tab Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Remove#getFile <em>File</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRemove()
 * @model
 * @generated
 */
public interface Remove extends Fun
{
  /**
   * Returns the value of the '<em><b>Remove Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Remove Element</em>' attribute.
   * @see #setRemoveElement(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRemove_RemoveElement()
   * @model
   * @generated
   */
  String getRemoveElement();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Remove#getRemoveElement <em>Remove Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Remove Element</em>' attribute.
   * @see #getRemoveElement()
   * @generated
   */
  void setRemoveElement(String value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRemove_Id()
   * @model
   * @generated
   */
  int getId();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Remove#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(int value);

  /**
   * Returns the value of the '<em><b>Tab Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tab Name</em>' attribute.
   * @see #setTabName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRemove_TabName()
   * @model
   * @generated
   */
  String getTabName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Remove#getTabName <em>Tab Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tab Name</em>' attribute.
   * @see #getTabName()
   * @generated
   */
  void setTabName(String value);

  /**
   * Returns the value of the '<em><b>File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>File</em>' attribute.
   * @see #setFile(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRemove_File()
   * @model
   * @generated
   */
  String getFile();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Remove#getFile <em>File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>File</em>' attribute.
   * @see #getFile()
   * @generated
   */
  void setFile(String value);

} // Remove
