/**
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Write CSV</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.WriteCSV#getWriteCSV <em>Write CSV</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.WriteCSV#getPath <em>Path</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.WriteCSV#getTabName <em>Tab Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.WriteCSV#getHeader <em>Header</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.WriteCSV#getOutputFile <em>Output File</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getWriteCSV()
 * @model
 * @generated
 */
public interface WriteCSV extends Fun
{
  /**
   * Returns the value of the '<em><b>Write CSV</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Write CSV</em>' attribute.
   * @see #setWriteCSV(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getWriteCSV_WriteCSV()
   * @model
   * @generated
   */
  String getWriteCSV();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.WriteCSV#getWriteCSV <em>Write CSV</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Write CSV</em>' attribute.
   * @see #getWriteCSV()
   * @generated
   */
  void setWriteCSV(String value);

  /**
   * Returns the value of the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' attribute.
   * @see #setPath(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getWriteCSV_Path()
   * @model
   * @generated
   */
  String getPath();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.WriteCSV#getPath <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' attribute.
   * @see #getPath()
   * @generated
   */
  void setPath(String value);

  /**
   * Returns the value of the '<em><b>Tab Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tab Name</em>' attribute.
   * @see #setTabName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getWriteCSV_TabName()
   * @model
   * @generated
   */
  String getTabName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.WriteCSV#getTabName <em>Tab Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tab Name</em>' attribute.
   * @see #getTabName()
   * @generated
   */
  void setTabName(String value);

  /**
   * Returns the value of the '<em><b>Header</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header</em>' attribute.
   * @see #setHeader(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getWriteCSV_Header()
   * @model
   * @generated
   */
  String getHeader();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.WriteCSV#getHeader <em>Header</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Header</em>' attribute.
   * @see #getHeader()
   * @generated
   */
  void setHeader(String value);

  /**
   * Returns the value of the '<em><b>Output File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output File</em>' attribute.
   * @see #setOutputFile(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getWriteCSV_OutputFile()
   * @model
   * @generated
   */
  String getOutputFile();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.WriteCSV#getOutputFile <em>Output File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Output File</em>' attribute.
   * @see #getOutputFile()
   * @generated
   */
  void setOutputFile(String value);

} // WriteCSV
