/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtext_tutorial.ui.internal.Xtext_tutorialActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Xtext_tutorialActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
