/**
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Add#getAddElement <em>Add Element</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Add#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAdd()
 * @model
 * @generated
 */
public interface Add extends Fun
{
  /**
   * Returns the value of the '<em><b>Add Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add Element</em>' attribute.
   * @see #setAddElement(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAdd_AddElement()
   * @model
   * @generated
   */
  String getAddElement();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Add#getAddElement <em>Add Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Add Element</em>' attribute.
   * @see #getAddElement()
   * @generated
   */
  void setAddElement(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(TypeJSON)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAdd_Value()
   * @model containment="true"
   * @generated
   */
  TypeJSON getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Add#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(TypeJSON value);

} // Add
