/**
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Get</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Get#getGetElement <em>Get Element</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Get#getId <em>Id</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getGet()
 * @model
 * @generated
 */
public interface Get extends Fun
{
  /**
   * Returns the value of the '<em><b>Get Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Get Element</em>' attribute.
   * @see #setGetElement(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getGet_GetElement()
   * @model
   * @generated
   */
  String getGetElement();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Get#getGetElement <em>Get Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Get Element</em>' attribute.
   * @see #getGetElement()
   * @generated
   */
  void setGetElement(String value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getGet_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Get#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

} // Get
