/**
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type JSON</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TypeJSON#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TypeJSON#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTypeJSON()
 * @model
 * @generated
 */
public interface TypeJSON extends TypeReference
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' attribute list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTypeJSON_Attribute()
   * @model unique="false"
   * @generated
   */
  EList<String> getAttribute();

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.TypeReference}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTypeJSON_Value()
   * @model containment="true"
   * @generated
   */
  EList<TypeReference> getValue();

} // TypeJSON
