/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import dsl_jq.ui.internal.Dsl_jqActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Dsl_jqActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
