/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class MyDslWebModule extends AbstractMyDslWebModule {
}
