/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import dsl_jq.ui.internal.Dsl_jqActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Dsl_jqActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Dsl_jqActivator activator = Dsl_jqActivator.getInstance();
		return activator != null ? activator.getInjector(Dsl_jqActivator.ORG_XTEXT_EXAMPLE_MYDSL_MYDSL) : null;
	}

}
