/**
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.example.mydsl.myDsl.JSON;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>JSON</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.JSONImpl#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.JSONImpl#getValueSTR <em>Value STR</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.JSONImpl#getValueINT <em>Value INT</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.JSONImpl#getValueID <em>Value ID</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JSONImpl extends MinimalEObjectImpl.Container implements JSON
{
  /**
   * The cached value of the '{@link #getAttribute() <em>Attribute</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttribute()
   * @generated
   * @ordered
   */
  protected EList<String> attribute;

  /**
   * The cached value of the '{@link #getValueSTR() <em>Value STR</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueSTR()
   * @generated
   * @ordered
   */
  protected EList<String> valueSTR;

  /**
   * The cached value of the '{@link #getValueINT() <em>Value INT</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueINT()
   * @generated
   * @ordered
   */
  protected EList<Integer> valueINT;

  /**
   * The cached value of the '{@link #getValueID() <em>Value ID</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueID()
   * @generated
   * @ordered
   */
  protected EList<String> valueID;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JSONImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.JSON;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getAttribute()
  {
    if (attribute == null)
    {
      attribute = new EDataTypeEList<String>(String.class, this, MyDslPackage.JSON__ATTRIBUTE);
    }
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getValueSTR()
  {
    if (valueSTR == null)
    {
      valueSTR = new EDataTypeEList<String>(String.class, this, MyDslPackage.JSON__VALUE_STR);
    }
    return valueSTR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Integer> getValueINT()
  {
    if (valueINT == null)
    {
      valueINT = new EDataTypeEList<Integer>(Integer.class, this, MyDslPackage.JSON__VALUE_INT);
    }
    return valueINT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getValueID()
  {
    if (valueID == null)
    {
      valueID = new EDataTypeEList<String>(String.class, this, MyDslPackage.JSON__VALUE_ID);
    }
    return valueID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.JSON__ATTRIBUTE:
        return getAttribute();
      case MyDslPackage.JSON__VALUE_STR:
        return getValueSTR();
      case MyDslPackage.JSON__VALUE_INT:
        return getValueINT();
      case MyDslPackage.JSON__VALUE_ID:
        return getValueID();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.JSON__ATTRIBUTE:
        getAttribute().clear();
        getAttribute().addAll((Collection<? extends String>)newValue);
        return;
      case MyDslPackage.JSON__VALUE_STR:
        getValueSTR().clear();
        getValueSTR().addAll((Collection<? extends String>)newValue);
        return;
      case MyDslPackage.JSON__VALUE_INT:
        getValueINT().clear();
        getValueINT().addAll((Collection<? extends Integer>)newValue);
        return;
      case MyDslPackage.JSON__VALUE_ID:
        getValueID().clear();
        getValueID().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.JSON__ATTRIBUTE:
        getAttribute().clear();
        return;
      case MyDslPackage.JSON__VALUE_STR:
        getValueSTR().clear();
        return;
      case MyDslPackage.JSON__VALUE_INT:
        getValueINT().clear();
        return;
      case MyDslPackage.JSON__VALUE_ID:
        getValueID().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.JSON__ATTRIBUTE:
        return attribute != null && !attribute.isEmpty();
      case MyDslPackage.JSON__VALUE_STR:
        return valueSTR != null && !valueSTR.isEmpty();
      case MyDslPackage.JSON__VALUE_INT:
        return valueINT != null && !valueINT.isEmpty();
      case MyDslPackage.JSON__VALUE_ID:
        return valueID != null && !valueID.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (attribute: ");
    result.append(attribute);
    result.append(", valueSTR: ");
    result.append(valueSTR);
    result.append(", valueINT: ");
    result.append(valueINT);
    result.append(", valueID: ");
    result.append(valueID);
    result.append(')');
    return result.toString();
  }

} //JSONImpl
