/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.example.mydsl.myDsl.Model

@ExtendWith(InjectionExtension)
@InjectWith(MyDslInjectorProvider)
class MyDslParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			read ("./MyPath.csv")
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val Python_Compiler cmpPython = new Python_Compiler(result)
		cmpPython.compileAndRun
	}
	
	//Test passé
	@Test
	def void TestPython1(){
		val result = parseHelper.parse('''
			writeJSON( "path_for_json.json",{"Var1" = "foo";})
		''')
		
		//Test de sécurité pour result.
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		//Run dans le compiler Python
		val Python_Compiler cmpPython = new Python_Compiler(result)
		cmpPython.compileAndRun
		
	}
	
	//Test passé
	@Test
	def void TestJQ1(){
		val result = parseHelper.parse('''
			writeJSON( "path_for_json.json",{"Var1" = "foo";})
		''')
		
		//Test de sécurité pour result.
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		
		//Run dans le compiler JQ
		val JQ_Compiler cmpJQ = new JQ_Compiler(result)
		cmpJQ.compileAndRun
		
	}
	
		//Test passé
		@Test
	def void TestPython2(){
		val result = parseHelper.parse('''
			writeCSV( "path_for_json.csv",{"Var1" = "foo";"Var2" = 0;})
		''')
		
		//Test de sécurité pour result.
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		//Run dans le compiler Python
		val Python_Compiler cmpPython = new Python_Compiler(result)
		cmpPython.compileAndRun
		
	}
	
	//Test passé
	@Test
	def void TestJQ2(){
		val result = parseHelper.parse('''
			writeCSV( "path_for_json.csv",{"Var1" = "foo";"Var2" = 0;})
		''')
		//Test de sécurité pour result.
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		
		//Run dans le compiler JQ
		val JQ_Compiler cmpJQ = new JQ_Compiler(result)
		cmpJQ.compileAndRun
		
	}
	
	@Test
	def void TestPython3(){
		val result = parseHelper.parse('''
			writeJSON( "path_for_json.json",{"Var1" = "foo"; "Var2" = { "Var3" = 0; "Var4" = "IHM";};})
		''')
		
		//Test de sécurité pour result.
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		//Run dans le compiler Python
		val Python_Compiler cmpPython = new Python_Compiler(result)
		cmpPython.compileAndRun
		
	}
	
	@Test
	def void TestPython4(){
		val result = parseHelper.parse('''
			writeCSV( "path_for_csv.csv",{"Var1" = "foo"; "Var2" = { "Var3" = 0; "Var4" = "IHM";};})
		''')
		
		//Test de sécurité pour result.
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		//Run dans le compiler Python
		val Python_Compiler cmpPython = new Python_Compiler(result)
		cmpPython.compileAndRun
		
	}
	
	@Test
	def void Test_Show_And_Read_Python(){
		val result = parseHelper.parse('''
			read("path_for_json.json")
			show
		''')
		
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val Python_Compiler cmpPython = new Python_Compiler(result)
		val o_PY = cmpPython.compileAndRun
	}
	
	@Test
	def void Test_Show_And_Read_JQ(){
		val result = parseHelper.parse('''
			read("path_for_json.json")
			show
		''')
		
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val JQ_Compiler cmpJQ = new JQ_Compiler(result)
		val o_JQ = cmpJQ.compileAndRun
	}
	
	@Test
	def void Test_Read_Add_And_Show_Python(){
		val result = parseHelper.parse('''
			read("path_for_json.json")
			add({"Var5" = "foo";})
			show
		''')
		
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val Python_Compiler cmpPython = new Python_Compiler(result)
		val o_PY = cmpPython.compileAndRun
	}
	
	@Test
	def void Test_Read_Get_And_Show_Python(){
		val result = parseHelper.parse('''
			read("path_for_json.json")
			get("Var1")
			show
		''')
		
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val Python_Compiler cmpPython = new Python_Compiler(result)
		val o_PY = cmpPython.compileAndRun
	}
	
	@Test
	def void Test_Read_Remove_And_Show_Python(){
		val result = parseHelper.parse('''
			read("path_for_json.json")
			remove("Var1")
			show
		''')
		
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val Python_Compiler cmpPython = new Python_Compiler(result)
		val o_PY = cmpPython.compileAndRun
	}
	
	@Test
	def void Test_Read_Write_Without_Data_Python(){
		val result = parseHelper.parse('''
			read("path_for_json.json")
			remove("Var1")
			writeJSON("path_for_json_new.json")
		''')
		
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val Python_Compiler cmpPython = new Python_Compiler(result)
		val o_PY = cmpPython.compileAndRun
	}
	
		@Test
	def void Test_Read_Write_Without_Data_Python_CSV(){
		val result = parseHelper.parse('''
			read("path_for_json.json")
			remove("Var1")
			writeCSV("path_for_json_new.csv")
		''')
		
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val Python_Compiler cmpPython = new Python_Compiler(result)
		val o_PY = cmpPython.compileAndRun
	}
}
