/**
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Remove;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Remove</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.RemoveImpl#getRemoveElement <em>Remove Element</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.RemoveImpl#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.RemoveImpl#getTabName <em>Tab Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.RemoveImpl#getFile <em>File</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RemoveImpl extends FunImpl implements Remove
{
  /**
   * The default value of the '{@link #getRemoveElement() <em>Remove Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRemoveElement()
   * @generated
   * @ordered
   */
  protected static final String REMOVE_ELEMENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRemoveElement() <em>Remove Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRemoveElement()
   * @generated
   * @ordered
   */
  protected String removeElement = REMOVE_ELEMENT_EDEFAULT;

  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final int ID_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected int id = ID_EDEFAULT;

  /**
   * The default value of the '{@link #getTabName() <em>Tab Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTabName()
   * @generated
   * @ordered
   */
  protected static final String TAB_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTabName() <em>Tab Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTabName()
   * @generated
   * @ordered
   */
  protected String tabName = TAB_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getFile() <em>File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFile()
   * @generated
   * @ordered
   */
  protected static final String FILE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFile() <em>File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFile()
   * @generated
   * @ordered
   */
  protected String file = FILE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RemoveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.REMOVE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRemoveElement()
  {
    return removeElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRemoveElement(String newRemoveElement)
  {
    String oldRemoveElement = removeElement;
    removeElement = newRemoveElement;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.REMOVE__REMOVE_ELEMENT, oldRemoveElement, removeElement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId(int newId)
  {
    int oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.REMOVE__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTabName()
  {
    return tabName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTabName(String newTabName)
  {
    String oldTabName = tabName;
    tabName = newTabName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.REMOVE__TAB_NAME, oldTabName, tabName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFile()
  {
    return file;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFile(String newFile)
  {
    String oldFile = file;
    file = newFile;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.REMOVE__FILE, oldFile, file));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.REMOVE__REMOVE_ELEMENT:
        return getRemoveElement();
      case MyDslPackage.REMOVE__ID:
        return getId();
      case MyDslPackage.REMOVE__TAB_NAME:
        return getTabName();
      case MyDslPackage.REMOVE__FILE:
        return getFile();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.REMOVE__REMOVE_ELEMENT:
        setRemoveElement((String)newValue);
        return;
      case MyDslPackage.REMOVE__ID:
        setId((Integer)newValue);
        return;
      case MyDslPackage.REMOVE__TAB_NAME:
        setTabName((String)newValue);
        return;
      case MyDslPackage.REMOVE__FILE:
        setFile((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.REMOVE__REMOVE_ELEMENT:
        setRemoveElement(REMOVE_ELEMENT_EDEFAULT);
        return;
      case MyDslPackage.REMOVE__ID:
        setId(ID_EDEFAULT);
        return;
      case MyDslPackage.REMOVE__TAB_NAME:
        setTabName(TAB_NAME_EDEFAULT);
        return;
      case MyDslPackage.REMOVE__FILE:
        setFile(FILE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.REMOVE__REMOVE_ELEMENT:
        return REMOVE_ELEMENT_EDEFAULT == null ? removeElement != null : !REMOVE_ELEMENT_EDEFAULT.equals(removeElement);
      case MyDslPackage.REMOVE__ID:
        return id != ID_EDEFAULT;
      case MyDslPackage.REMOVE__TAB_NAME:
        return TAB_NAME_EDEFAULT == null ? tabName != null : !TAB_NAME_EDEFAULT.equals(tabName);
      case MyDslPackage.REMOVE__FILE:
        return FILE_EDEFAULT == null ? file != null : !FILE_EDEFAULT.equals(file);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (removeElement: ");
    result.append(removeElement);
    result.append(", id: ");
    result.append(id);
    result.append(", tabName: ");
    result.append(tabName);
    result.append(", file: ");
    result.append(file);
    result.append(')');
    return result.toString();
  }

} //RemoveImpl
